# Generated by Django 5.2.14 on 2026-06-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocodedaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
