# Generated by Django 5.2.14 on 2026-06-13 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0069_menuelement_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartElement',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='builder.element')),
                ('chart_type', models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('pie', 'Pie'), ('doughnut', 'Doughnut'), ('scatter', 'Scatter')], default='bar', max_length=32)),
                ('data_source', models.ForeignKey(blank=True, help_text='Builder data source providing grouped-aggregate rows for chart rendering.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.datasource')),
            ],
            options={
                'abstract': False,
            },
            bases=('builder.element',),
        ),
    ]
