# Generated by Django 5.2.14 on 2026-06-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0070_chartelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricElement',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='builder.element')),
                ('data_source', models.ForeignKey(blank=True, help_text='Builder data source providing aggregate rows for metric rendering.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.datasource')),
            ],
            options={
                'abstract': False,
            },
            bases=('builder.element',),
        ),
    ]
