# Generated by Django 5.2.14 on 2026-06-06 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0211_viewsort_viewgroupby_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "editable_by_role",
                    models.CharField(
                        choices=[
                            ("VIEWER", "Viewer"),
                            ("COMMENTER", "Commenter"),
                            ("EDITOR", "Editor"),
                            ("ADMIN", "Admin"),
                        ],
                        help_text=(
                            "The minimum fixed-tier role (Viewer/Commenter/Editor/"
                            "Admin) allowed to edit this field's values and config. "
                            "Effective roles below this threshold are denied writes "
                            "(HTTP 403) but keep read access. Absence of a row means "
                            "the field is unrestricted."
                        ),
                        max_length=32,
                    ),
                ),
                (
                    "field",
                    models.OneToOneField(
                        help_text="The field this edit-restriction rule applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission",
                        to="database.field",
                    ),
                ),
            ],
        ),
    ]
