# Generated by Django 5.2.14 on 2026-06-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    """Story 1.5: add the read/visibility threshold column to the 1.4
    ``FieldPermission`` rule row, and relax ``editable_by_role`` to be nullable.

    ``readable_by_role`` is the minimum fixed-tier role allowed to *see* the
    field. Null/absent (the default) preserves pre-1.5 behavior: the field is
    visible to all.

    ``editable_by_role`` becomes nullable so a row may carry ONLY a read
    threshold (a hidden-but-not-edit-restricted field). The two thresholds are
    independent (Story 1.5 Task 2 — "do not couple them"). 1.4 rows always
    stored an explicit edit role, so this is purely additive. Reverting both
    operations restores 1.4 behavior.
    """

    dependencies = [
        ("database", "0212_fieldpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldpermission",
            name="readable_by_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VIEWER", "Viewer"),
                    ("COMMENTER", "Commenter"),
                    ("EDITOR", "Editor"),
                    ("ADMIN", "Admin"),
                ],
                default=None,
                help_text=(
                    "Story 1.5 read/visibility threshold: the minimum fixed-tier "
                    "role (Viewer/Commenter/Editor/Admin) allowed to *see* this "
                    "field. Effective roles below this threshold never receive the "
                    "field's value on any read surface (views, search, REST, "
                    "WebSocket) and cannot filter or sort on it. Null/absent (the "
                    "default) means the field is visible to all — purely additive, "
                    "independent of editable_by_role."
                ),
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fieldpermission",
            name="editable_by_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VIEWER", "Viewer"),
                    ("COMMENTER", "Commenter"),
                    ("EDITOR", "Editor"),
                    ("ADMIN", "Admin"),
                ],
                default=None,
                help_text=(
                    "The minimum fixed-tier role (Viewer/Commenter/Editor/Admin) "
                    "allowed to edit this field's values and config. Effective "
                    "roles below this threshold are denied writes (HTTP 403) but "
                    "keep read access. Null/absent means the field is not "
                    "edit-restricted (Story 1.5 allows a read-restricted field "
                    "that carries no edit restriction, so the two thresholds are "
                    "independent). Absence of a row means the field is fully "
                    "unrestricted."
                ),
                max_length=32,
                null=True,
            ),
        ),
    ]
