# Generated by Django 5.2.14 on 2026-06-07 06:37
# Generated for Story 2.1: Currency Field — adds CurrencyField metadata model (multi-table inheritance from NumberField).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0215_view_password_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyField',
            fields=[
                ('numberfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.numberfield')),
                ('currency_symbol', models.CharField(default='$', help_text='The currency symbol to display before the value.', max_length=10)),
            ],
            bases=('database.numberfield',),
        ),
        migrations.AlterField(
            model_name='formview',
            name='mode',
            field=models.TextField(choices="[('form', 'form')]", default='form', help_text='Configurable mode of the form.', max_length=64),
        ),
    ]
