# Generated by Django 5.2.14 on 2026-06-07 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0216_currencyfield_alter_formview_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentField',
            fields=[
                ('numberfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.numberfield')),
            ],
            bases=('database.numberfield',),
        ),
        migrations.AlterField(
            model_name='formview',
            name='mode',
            field=models.TextField(choices="[('form', 'form')]", default='form', help_text='Configurable mode of the form.', max_length=64),
        ),
    ]
