# Generated by Django 5.2.14 on 2026-06-10 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0217_percentfield_alter_formview_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeField',
            fields=[
                ('textfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.textfield')),
                ('barcode_type', models.CharField(choices=[('qr', 'QR Code'), ('code128', 'Code 128')], default='qr', help_text='The barcode symbology to render (qr or code128).', max_length=20)),
            ],
            bases=('database.textfield',),
        ),
        migrations.AlterField(
            model_name='formview',
            name='mode',
            field=models.TextField(choices="[('form', 'form')]", default='form', help_text='Configurable mode of the form.', max_length=64),
        ),
    ]
