# Generated by Django 5.2.14 on 2026-06-10 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0218_barcodefield_alter_formview_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningCountField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.field')),
                ('filter_conditions', models.JSONField(blank=True, default=None, help_text='Optional filter conditions in Baserow ViewFilter format. Null means count all non-trashed rows in the table (whole-table scope).', null=True)),
            ],
            bases=('database.field',),
        ),
        migrations.AlterField(
            model_name='formview',
            name='mode',
            field=models.TextField(choices="[('form', 'form'), ('survey', 'survey')]", default='form', help_text='Configurable mode of the form.', max_length=64),
        ),
    ]
