# Generated by Django 5.2.14 on 2026-06-10 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0219_runningcountfield_alter_formview_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="KanbanView",
            fields=[
                (
                    "view_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="core_kanban_view",
                        serialize=False,
                        to="database.view",
                    ),
                ),
                (
                    "card_cover_image_field",
                    models.ForeignKey(
                        blank=True,
                        help_text="References a file field of which the first image "
                        "must be shown as card cover image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="core_kanban_view_card_cover_field",
                        to="database.field",
                    ),
                ),
                (
                    "single_select_field",
                    models.ForeignKey(
                        blank=True,
                        help_text="The single select field by which the rows are "
                        "grouped into columns. Rows without a value are shown in the "
                        "'Uncategorized' column.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="core_kanban_view_single_select_field",
                        to="database.field",
                    ),
                ),
            ],
            options={
                "db_table": "database_corekanbanview",
            },
            bases=("database.view",),
        ),
        migrations.CreateModel(
            name="KanbanViewFieldOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=True,
                        help_text="Whether or not the field should be hidden in the "
                        "card.",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        default=32767,
                        help_text="The order that the field has in the form. Lower "
                        "value is first.",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="database.field",
                    ),
                ),
                (
                    "kanban_view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.kanbanview",
                    ),
                ),
            ],
            options={
                "db_table": "database_corekanbanviewfieldoptions",
                "ordering": ("order", "field_id"),
                "unique_together": {("kanban_view", "field")},
            },
        ),
        migrations.AddField(
            model_name="kanbanview",
            name="field_options",
            field=models.ManyToManyField(
                related_name="+",
                through="database.KanbanViewFieldOptions",
                to="database.field",
            ),
        ),
    ]
