# Generated by Django 5.2.14 on 2026-06-10 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0220_kanbanview_kanbanviewfieldoptions"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarView",
            fields=[
                (
                    "view_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="core_calendar_view",
                        serialize=False,
                        to="database.view",
                    ),
                ),
                (
                    "date_field",
                    models.ForeignKey(
                        blank=True,
                        help_text="The date field by which the rows are positioned "
                        "on the calendar. Rows without a value are shown in the "
                        "unscheduled tray.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="core_calendar_view_date_field",
                        to="database.field",
                    ),
                ),
                (
                    "end_date_field",
                    models.ForeignKey(
                        blank=True,
                        help_text="An optional date field marking the end of a "
                        "multi-day event. When set, rows span from `date_field` to "
                        "`end_date_field`.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="core_calendar_view_end_date_field",
                        to="database.field",
                    ),
                ),
            ],
            options={
                "db_table": "database_corecalendarview",
            },
            bases=("database.view",),
        ),
        migrations.CreateModel(
            name="CalendarViewFieldOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=True,
                        help_text="Whether or not the field should be hidden in the "
                        "card.",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        default=32767,
                        help_text="The order that the field has in the form. Lower "
                        "value is first.",
                    ),
                ),
                (
                    "calendar_view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.calendarview",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="database.field",
                    ),
                ),
            ],
            options={
                "db_table": "database_corecalendarviewfieldoptions",
                "ordering": ("order", "field_id"),
                "unique_together": {("calendar_view", "field")},
            },
        ),
        migrations.AddField(
            model_name="calendarview",
            name="field_options",
            field=models.ManyToManyField(
                related_name="+",
                through="database.CalendarViewFieldOptions",
                to="database.field",
            ),
        ),
    ]
