# Generated by Django 5.2.14 on 2026-06-10 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0221_calendarview_calendarviewfieldoptions"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineView",
            fields=[
                (
                    "view_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="core_timeline_view",
                        serialize=False,
                        to="database.view",
                    ),
                ),
                (
                    "start_date_field",
                    models.ForeignKey(
                        blank=True,
                        help_text="The date field positioning the left edge of each "
                        "bar on the timeline. A row is only rendered as a bar when "
                        "both the start and end date fields have a value; otherwise "
                        "it is shown in the unscheduled tray.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="core_timeline_view_start_date_field",
                        to="database.field",
                    ),
                ),
                (
                    "end_date_field",
                    models.ForeignKey(
                        blank=True,
                        help_text="The date field positioning the right edge of each "
                        "bar on the timeline. A row is only rendered as a bar when "
                        "both the start and end date fields have a value; otherwise "
                        "it is shown in the unscheduled tray.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="core_timeline_view_end_date_field",
                        to="database.field",
                    ),
                ),
                (
                    "timescale",
                    models.CharField(
                        choices=[
                            ("day", "day"),
                            ("week", "week"),
                            ("month", "month"),
                        ],
                        default="month",
                        help_text="The persisted zoom level of the time axis: day, "
                        "week or month.",
                        max_length=8,
                    ),
                ),
            ],
            options={
                "db_table": "database_coretimelineview",
            },
            bases=("database.view",),
        ),
        migrations.CreateModel(
            name="TimelineViewFieldOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=True,
                        help_text="Whether or not the field should be hidden in the "
                        "card.",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        default=32767,
                        help_text="The order that the field has in the form. Lower "
                        "value is first.",
                    ),
                ),
                (
                    "timeline_view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.timelineview",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="database.field",
                    ),
                ),
            ],
            options={
                "db_table": "database_coretimelineviewfieldoptions",
                "ordering": ("order", "field_id"),
                "unique_together": {("timeline_view", "field")},
            },
        ),
        migrations.AddField(
            model_name="timelineview",
            name="field_options",
            field=models.ManyToManyField(
                related_name="+",
                through="database.TimelineViewFieldOptions",
                to="database.field",
            ),
        ),
    ]
