# Generated by Django 5.2.14 on 2026-06-10 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0222_timelineview_timelineviewfieldoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanttView',
            fields=[
                ('view_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='gantt_view', serialize=False, to='database.view')),
                ('timescale', models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month')], default='month', help_text='The persisted zoom level of the time axis: day, week or month. Mapped to the Frappe Gantt `view_mode` on the frontend.', max_length=8)),
                ('end_date_field', models.ForeignKey(blank=True, help_text='The date field positioning the right edge of each bar on the gantt. A row is only rendered as a bar when both the start and end date fields have a value; otherwise it is shown in the unscheduled tray.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gantt_view_end_date_field', to='database.field')),
                ('start_date_field', models.ForeignKey(blank=True, help_text='The date field positioning the left edge of each bar on the gantt. A row is only rendered as a bar when both the start and end date fields have a value; otherwise it is shown in the unscheduled tray.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gantt_view_start_date_field', to='database.field')),
            ],
            options={
                'db_table': 'database_ganttview',
            },
            bases=('database.view',),
        ),
        migrations.CreateModel(
            name='GanttViewFieldOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=True, help_text='Whether or not the field should be hidden in the card.')),
                ('order', models.SmallIntegerField(default=32767, help_text='The order that the field has in the form. Lower value is first.')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.field')),
                ('gantt_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.ganttview')),
            ],
            options={
                'db_table': 'database_ganttviewfieldoptions',
                'ordering': ('order', 'field_id'),
                'unique_together': {('gantt_view', 'field')},
            },
        ),
        migrations.AddField(
            model_name='ganttview',
            name='field_options',
            field=models.ManyToManyField(related_name='gantt_view_field_options', through='database.GanttViewFieldOptions', to='database.field'),
        ),
    ]
