# Generated by Django 5.2.14 on 2026-06-10 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0223_ganttview_ganttviewfieldoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predecessor_row_id', models.PositiveIntegerField(help_text='The id of the row that must come first (the predecessor).')),
                ('successor_row_id', models.PositiveIntegerField(help_text='The id of the dependent row that comes after (the successor).')),
                ('dependency_type', models.CharField(choices=[('FS', 'FS')], default='FS', help_text='The dependency semantics. v1 ships finish-to-start (FS) only; the column exists so later stories can add SS/FF/SF without a migration, but any non-FS value is rejected by the handler for now.', max_length=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(help_text='The table whose rows this dependency edge connects.', on_delete=django.db.models.deletion.CASCADE, related_name='task_dependencies', to='database.table')),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['table', 'successor_row_id'], name='database_ta_table_i_239120_idx'), models.Index(fields=['table', 'predecessor_row_id'], name='database_ta_table_i_c3edc2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('predecessor_row_id', models.F('successor_row_id')), _negated=True), name='task_dependency_no_self_loop')],
                'unique_together': {('table', 'predecessor_row_id', 'successor_row_id')},
            },
        ),
    ]
