# Generated by Django 5.2.14 on 2026-06-11 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0224_taskdependency'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapView',
            fields=[
                ('view_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='map_view', serialize=False, to='database.view')),
                ('address_field', models.ForeignKey(blank=True, help_text='Text/long-text field whose value is geocoded to produce pin coordinates. Mutually exclusive with lat_field/lng_field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_view_address_field', to='database.field')),
                ('lat_field', models.ForeignKey(blank=True, help_text='Numeric field holding the latitude value. Used with lng_field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_view_lat_field', to='database.field')),
                ('lng_field', models.ForeignKey(blank=True, help_text='Numeric field holding the longitude value. Used with lat_field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_view_lng_field', to='database.field')),
            ],
            options={
                'db_table': 'database_mapview',
            },
            bases=('database.view',),
        ),
        migrations.CreateModel(
            name='MapViewFieldOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=True, help_text='Whether or not the field should be hidden.')),
                ('order', models.SmallIntegerField(default=32767, help_text='The order that the field has. Lower value is first.')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.field')),
                ('map_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.mapview')),
            ],
            options={
                'db_table': 'database_mapviewfieldoptions',
                'ordering': ('order', 'field_id'),
                'unique_together': {('map_view', 'field')},
            },
        ),
        migrations.AddField(
            model_name='mapview',
            name='field_options',
            field=models.ManyToManyField(related_name='map_view_field_options', through='database.MapViewFieldOptions', to='database.field'),
        ),
    ]
