# Generated by Django 5.2.14 on 2026-06-14 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0227_rowcommentsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # database_rowcomment was already created by migration 0226 using IF NOT EXISTS
        # raw SQL (safe for both OSS and premium environments). Skip the CREATE TABLE
        # here but register the model in Django's migration state so subsequent
        # AddField/AddIndex operations can reference it.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='RowComment',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('row_id', models.PositiveIntegerField(db_index=True)),
                        ('message', models.JSONField(default=dict, help_text='Tiptap document JSON.')),
                        ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                        ('updated_on', models.DateTimeField(auto_now=True)),
                        ('deleted_on', models.DateTimeField(db_index=True, null=True)),
                        ('trashed', models.BooleanField(db_index=True, default=False)),
                    ],
                    options={
                        'db_table': 'database_rowcomment',
                        'ordering': ['created_on'],
                    },
                ),
            ],
        ),
        migrations.RenameIndex(
            model_name='rowcommentsubscription',
            new_name='database_ro_table_i_ea49b3_idx',
            old_name='database_ro_table_i_rowsub_idx',
        ),
        migrations.AlterField(
            model_name='fieldpermission',
            name='editable_by_role',
            field=models.CharField(blank=True, choices=[('VIEWER', 'Viewer'), ('COMMENTER', 'Commenter'), ('EDITOR', 'Editor'), ('ADMIN', 'Admin'), ('INTERFACE_ONLY', 'Interface Collaborator')], default=None, help_text="The minimum fixed-tier role (Viewer/Commenter/Editor/Admin) allowed to edit this field's values and config. Effective roles below this threshold are denied writes (HTTP 403) but keep read access. Null/absent means the field is not edit-restricted (Story 1.5 allows a read-restricted field that carries no edit restriction, so the two thresholds are independent). Absence of a row means the field is fully unrestricted.", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='fieldpermission',
            name='field',
            field=models.OneToOneField(help_text='The field this edit-restriction rule applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='core_permission', to='database.field'),
        ),
        migrations.AlterField(
            model_name='fieldpermission',
            name='readable_by_role',
            field=models.CharField(blank=True, choices=[('VIEWER', 'Viewer'), ('COMMENTER', 'Commenter'), ('EDITOR', 'Editor'), ('ADMIN', 'Admin'), ('INTERFACE_ONLY', 'Interface Collaborator')], default=None, help_text="Story 1.5 read/visibility threshold: the minimum fixed-tier role (Viewer/Commenter/Editor/Admin) allowed to *see* this field. Effective roles below this threshold never receive the field's value on any read surface (views, search, REST, WebSocket) and cannot filter or sort on it. Null/absent (the default) means the field is visible to all — purely additive, independent of editable_by_role.", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='formview',
            name='mode',
            field=models.TextField(choices="[('form', 'form'), ('survey', 'survey')]", default='form', help_text='Configurable mode of the form.', max_length=64),
        ),
        # table_id and user_id columns already exist (created by migration 0226).
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='rowcomment',
                    name='table',
                    field=models.ForeignKey(help_text='The table the row this comment is for is found in.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='database.table'),
                ),
                migrations.AddField(
                    model_name='rowcomment',
                    name='user',
                    field=models.ForeignKey(help_text='The user who made the comment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='rowcomment',
            index=models.Index(fields=['table', 'row_id'], name='database_ro_table_i_266bb4_idx'),
        ),
    ]
