# Generated by Django 5.2.14 on 2026-06-12 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_widget_dashboarddatasource_summarywidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.widget')),
                ('chart_type', models.CharField(choices=[('bar', 'Bar'), ('pie', 'Pie'), ('doughnut', 'Doughnut')], default='bar', max_length=32)),
                ('data_source', models.ForeignKey(help_text='Data source providing grouped-aggregate rows for chart rendering.', on_delete=django.db.models.deletion.PROTECT, to='dashboard.dashboarddatasource')),
            ],
            options={
                'abstract': False,
            },
            bases=('dashboard.widget',),
        ),
    ]
