# Generated by Django 5.2.14 on 2026-06-14 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_dashboard_public_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartwidget',
            name='data_source',
            field=models.ForeignKey(help_text='Data source providing grouped-aggregate rows for chart rendering.', on_delete=django.db.models.deletion.PROTECT, related_name='core_chartwidget_set', to='dashboard.dashboarddatasource'),
        ),
        migrations.AlterField(
            model_name='chartwidget',
            name='widget_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_chartwidget', serialize=False, to='dashboard.widget'),
        ),
    ]
