# Generated by Django 5.2.14 on 2026-06-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baserow_premium', '0031_ai_field_scheduled_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rowcomment',
            options={'managed': False, 'ordering': ('-created_on',)},
        ),
    ]
