# Generated by Django 5.2.14 on 2026-06-12 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_rbac_roleassignment'),
        ('database', '0225_mapview_mapviewfieldoptions'),
        ('integrations', '0027_coresmtpemailservice_use_instance_smtp_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBaserowGroupedAggregateRows',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.service')),
                ('filter_type', models.CharField(choices=[('AND', 'And'), ('OR', 'Or')], default='AND', help_text='Indicates whether all the rows should apply to all filters (AND) or to any filter (OR).', max_length=3)),
                ('aggregation_type', models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('avg', 'Average'), ('min', 'Minimum'), ('max', 'Maximum')], default='count', help_text='Aggregation function: count/sum/avg/min/max.', max_length=16)),
                ('group_by_field', models.ForeignKey(help_text='The field to group by (provides categories).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grouped_aggregate_group_by', to='database.field')),
                ('series_field', models.ForeignKey(blank=True, help_text='Optional secondary group-by for multi-series charts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grouped_aggregate_series', to='database.field')),
                ('table', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.table')),
                ('value_field', models.ForeignKey(blank=True, help_text='The field to aggregate. May be null for count aggregation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grouped_aggregate_value', to='database.field')),
                ('view', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.view')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.service', models.Model),
        ),
    ]
