# Generated by Django 5.2.14 on 2026-06-14 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_rename_core_interf_user_id_workspace_idx_core_interf_user_id_3aab71_idx_and_more'),
        ('database', '0228_rowcomment_and_more'),
        ('integrations', '0028_localbaserowgroupedaggregaterows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localbaserowgroupedaggregaterows',
            name='service_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_localbaserowgroupedaggregaterows', serialize=False, to='core.service'),
        ),
        migrations.AlterField(
            model_name='localbaserowgroupedaggregaterows',
            name='table',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_localbaserowgroupedaggregaterows_set', to='database.table'),
        ),
        migrations.AlterField(
            model_name='localbaserowgroupedaggregaterows',
            name='view',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_localbaserowgroupedaggregaterows_set', to='database.view'),
        ),
    ]
