# Generated by Django 5.2.14 on 2026-06-06 11:33

import baserow.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Legacy permission strings (mirrored locally so the migration is self-contained and
# does not import application code).
LEGACY_ADMIN = "ADMIN"
# RBAC fixed-tier role values (see core/rbac/roles.py).
ROLE_ADMIN = "ADMIN"
ROLE_EDITOR = "EDITOR"


# noinspection PyPep8Naming,PyUnusedLocal
def forward(apps, schema_editor):
    """Derive a workspace-scoped RoleAssignment from each existing WorkspaceUser.

    ADMIN -> Admin, MEMBER (and anything else) -> Editor. This guarantees no silent
    write-loss: today's members (write-capable) become Editor (write-capable), not
    Viewer/Commenter. The legacy WorkspaceUser.permissions field is NOT modified.

    WorkspaceInvitation rows carry a permissions string but no user subject, so no
    RoleAssignment is derivable until the invitation is accepted (handled in a later
    story); their legacy permissions field is left intact.
    """

    WorkspaceUser = apps.get_model("core", "WorkspaceUser")
    RoleAssignment = apps.get_model("core", "RoleAssignment")

    to_create = []
    for workspace_user in WorkspaceUser.objects.all().iterator():
        role = (
            ROLE_ADMIN
            if LEGACY_ADMIN in (workspace_user.permissions or "")
            else ROLE_EDITOR
        )
        to_create.append(
            RoleAssignment(
                user_id=workspace_user.user_id,
                workspace_id=workspace_user.workspace_id,
                application_id=None,
                role=role,
            )
        )

    RoleAssignment.objects.bulk_create(to_create, batch_size=1000)


# noinspection PyPep8Naming,PyUnusedLocal
def reverse(apps, schema_editor):
    """Documented rollback: remove every derived RoleAssignment.

    Safe because the legacy WorkspaceUser.permissions field was never altered, so the
    pre-1.2 ADMIN/MEMBER state is fully restored with no data loss.
    """

    RoleAssignment = apps.get_model("core", "RoleAssignment")
    RoleAssignment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_alter_workspaceinvitation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('VIEWER', 'Viewer'), ('COMMENTER', 'Commenter'), ('EDITOR', 'Editor'), ('ADMIN', 'Admin')], help_text='The fixed role tier (Viewer / Commenter / Editor / Admin).', max_length=32)),
                ('application', models.ForeignKey(blank=True, help_text='When set, the assignment is scoped to this database/application and overrides the workspace-scoped assignment for that database. When null, the assignment is workspace-scoped.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbac_role_assignments', to='core.application')),
                ('user', models.ForeignKey(help_text='The user (subject) the role is granted to.', on_delete=django.db.models.deletion.CASCADE, related_name='rbac_role_assignments', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='The workspace the assignment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='rbac_role_assignments', to='core.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'workspace'], name='core_roleas_user_id_db55c9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('application__isnull', True)), fields=('user', 'workspace'), name='unique_workspace_scoped_role_assignment'), models.UniqueConstraint(condition=models.Q(('application__isnull', False)), fields=('user', 'workspace', 'application'), name='unique_database_scoped_role_assignment')],
            },
        ),
        migrations.RunPython(forward, reverse),
    ]
