# Generated by Story 6.3 — adds INTERFACE_ONLY to RoleAssignment.role choices.
# No data migration needed: no existing rows use this role value.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0115_rbac_roleassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roleassignment",
            name="role",
            field=models.CharField(
                choices=[
                    ("VIEWER", "Viewer"),
                    ("COMMENTER", "Commenter"),
                    ("EDITOR", "Editor"),
                    ("ADMIN", "Admin"),
                    ("INTERFACE_ONLY", "Interface Collaborator"),
                ],
                help_text="The fixed role tier (Viewer / Commenter / Editor / Admin) or interface-only.",
                max_length=32,
            ),
        ),
    ]
