# Generated by Story 6.3 — InterfaceCollaboratorPageGrant model.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0116_rbac_roleassignment_interface_only"),
        ("builder", "0073_recordreviewelement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterfaceCollaboratorPageGrant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interface_page_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interface_page_grants",
                        to="core.workspace",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interface_page_grants",
                        to="builder.page",
                    ),
                ),
            ],
            options={
                "app_label": "core",
            },
        ),
        migrations.AlterUniqueTogether(
            name="interfacecollaboratorpagegrant",
            unique_together={("user", "page")},
        ),
        migrations.AddIndex(
            model_name="interfacecollaboratorpagegrant",
            index=models.Index(
                fields=["user", "workspace"],
                name="core_interf_user_id_workspace_idx",
            ),
        ),
    ]
