# Generated by Django 5.2.14 on 2026-06-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_interfacecollaboratorpagegrant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='interfacecollaboratorpagegrant',
            new_name='core_interf_user_id_3aab71_idx',
            old_name='core_interf_user_id_workspace_idx',
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('VIEWER', 'Viewer'), ('COMMENTER', 'Commenter'), ('EDITOR', 'Editor'), ('ADMIN', 'Admin'), ('INTERFACE_ONLY', 'Interface Collaborator')], help_text='The fixed role tier (Viewer / Commenter / Editor / Admin).', max_length=32),
        ),
    ]
